#!/usr/bin/env python3
"""Generate THIRD-PARTY-NOTICES.md from the shipped binary's dependency graph.

The compliance artifact NFR-CR-02 requires: a single file aggregating
third-party attributions (crates, tree-sitter grammars, bundled SQLite) that
ships with every release (wired via `include` in dist-workspace.toml).

Scope = exactly the dependencies that can reach the distributed `logos`
binary: `cargo tree -p logos -e normal,build` (default features — the shipped
artifact, ADR-16), resolved against `cargo metadata` for license/repository
fields. Dev-dependencies never ship and are excluded by construction.

Run from the workspace root; commit the regenerated file:

    python3 scripts/gen-third-party-notices.py

Exit codes: 0 ok · 1 cargo invocation failed · 2 a shipped dependency is
missing license metadata (fix or vendor an attribution by hand).
"""

import json
import subprocess
import sys
from pathlib import Path

OUT = Path("THIRD-PARTY-NOTICES.md")
DISTRIBUTED_PACKAGE = "logos"
# The web UI's build-time-only npm project (CR-049, FR-UI-22, ADR-43). Its
# *production* dependency closure is bundled into the embedded SPA and therefore
# distributed in the `--features ui` binary, so its licenses join this artifact
# (NFR-CR-01). Build-time devDependencies (Vite, TypeScript, …) never ship and
# are excluded by the `dev` marker in the lockfile.
NPM_LOCKFILE = Path("web/ui/package-lock.json")

HEADER = """\
# Third-Party Notices

Logos is distributed under the [MIT license](LICENSE) (NFR-CR-01).

The distributed `logos` binary statically links the third-party Rust crates
and C libraries below (NFR-CR-02). Each is used under the license indicated;
the full license texts are available from the linked repositories. The
bundled SQLite amalgamation (via `rusqlite`'s `bundled` feature) is public
domain. Tree-sitter grammars are compiled in as generated C parse tables
under their crates' licenses listed below.

The `--features ui` release binary additionally embeds the web dashboard SPA
([CR-049](docs/requests/CR-049-decouple-web-ui-into-embedded-spa.md),
FR-UI-22): the **bundled JavaScript** section below covers the production npm
dependency closure compiled into that embedded bundle. The build-time-only
toolchain (Vite, TypeScript, …) does not ship and is excluded.

This file is generated by `scripts/gen-third-party-notices.py`; regenerate it
whenever `Cargo.lock` or `web/ui/package-lock.json` changes the shipped
dependency set.

| Crate | Version | License | Source |
|-------|---------|---------|--------|
"""

FOOTER = """\

## Non-crate components

| Component | License | Notes |
|-----------|---------|-------|
| SQLite (bundled amalgamation, FTS5 enabled) | Public Domain | statically compiled via `rusqlite/bundled` |
"""


def run(args: list[str]) -> str:
    try:
        return subprocess.run(
            args, check=True, capture_output=True, text=True
        ).stdout
    except (subprocess.CalledProcessError, FileNotFoundError) as err:
        print(f"error: {' '.join(args)}: {err}", file=sys.stderr)
        sys.exit(1)


def shipped_package_ids() -> set[str]:
    """Package IDs reachable from the distributed binary (normal+build deps)."""
    out = run(
        [
            "cargo", "tree", "-p", DISTRIBUTED_PACKAGE,
            "-e", "normal,build",
            "--prefix", "none",
            "--format", "{p}",
        ]
    )
    ids = set()
    for line in out.splitlines():
        line = line.strip().removesuffix(" (*)")
        if line:
            # "name vX.Y.Z (path)" — key by (name, version).
            parts = line.split()
            if len(parts) >= 2:
                ids.add((parts[0], parts[1].lstrip("v")))
    return ids


def bundled_js_section() -> str:
    """The bundled-JavaScript notices section, derived from the npm lockfile.

    Reads `web/ui/package-lock.json` (lockfile v3) and lists the **production**
    dependency closure — every `node_modules/*` entry not marked `dev` — that is
    compiled into the embedded SPA bundle and therefore distributed (NFR-CR-01).
    Name/version/license come straight from the lockfile (deterministic, no
    `node_modules` needed); the source links to the npm package page. Returns an
    empty string if the lockfile is absent (a Rust-only checkout), so the Rust
    notices still regenerate.
    """
    if not NPM_LOCKFILE.exists():
        return ""
    lock = json.loads(NPM_LOCKFILE.read_text())
    rows, missing = [], []
    for key, pkg in lock.get("packages", {}).items():
        if not key.startswith("node_modules/") or pkg.get("dev"):
            continue
        # The package name is the segment after the last `node_modules/` (handles
        # nested and scoped `@scope/name` paths alike).
        name = key.rsplit("node_modules/", 1)[1]
        version = pkg.get("version", "?")
        license_ = pkg.get("license")
        if not license_:
            missing.append(f"{name} {version}")
            continue
        source = f"https://www.npmjs.com/package/{name}"
        rows.append(f"| {name} | {version} | {license_} | {source} |")

    if missing:
        print(
            "error: bundled npm dependencies without license metadata in the "
            "lockfile: " + ", ".join(missing),
            file=sys.stderr,
        )
        sys.exit(2)

    rows.sort()
    return (
        "\n## Bundled JavaScript (web UI SPA, `--features ui`)\n\n"
        "Production npm dependencies compiled into the embedded dashboard bundle "
        "(CR-049, FR-UI-22). Build-time-only devDependencies are excluded.\n\n"
        "| Package | Version | License | Source |\n"
        "|---------|---------|---------|--------|\n" + "\n".join(rows) + "\n"
    )


def main() -> None:
    shipped = shipped_package_ids()
    meta = json.loads(run(["cargo", "metadata", "--format-version", "1"]))
    workspace = set(meta["workspace_members"])

    rows, missing = [], []
    for pkg in meta["packages"]:
        if pkg["id"] in workspace:
            continue
        if (pkg["name"], pkg["version"]) not in shipped:
            continue
        license_ = pkg.get("license")
        # Some crates set `license-file` instead of the SPDX `license` field
        # (e.g. tree-sitter-graphql 0.1.0 ships a `LICENSE` file but no SPDX
        # expression). Resolve those honestly by reading the bundled license
        # rather than fabricating an id: derive the well-known SPDX id from the
        # file's first non-empty line, falling back to that line verbatim.
        if not license_ and pkg.get("license_file"):
            lic_path = Path(pkg["manifest_path"]).parent / pkg["license_file"]
            try:
                first = next(
                    (ln.strip() for ln in lic_path.read_text().splitlines() if ln.strip()),
                    "",
                )
            except OSError:
                first = ""
            low = first.lower()
            if low.startswith("mit license") or low == "mit":
                license_ = "MIT (from bundled LICENSE file)"
            elif "apache license" in low:
                license_ = "Apache-2.0 (from bundled LICENSE file)"
            elif first:
                license_ = f"{first} (from bundled LICENSE file)"
        if not license_:
            missing.append(f"{pkg['name']} {pkg['version']}")
            continue
        source = pkg.get("repository") or "https://crates.io/crates/" + pkg["name"]
        rows.append(
            f"| {pkg['name']} | {pkg['version']} | {license_} | {source} |"
        )

    if missing:
        print(
            "error: shipped dependencies without license metadata: "
            + ", ".join(missing),
            file=sys.stderr,
        )
        sys.exit(2)

    rows.sort()
    OUT.write_text(HEADER + "\n".join(rows) + "\n" + bundled_js_section() + FOOTER)
    print(f"wrote {OUT} ({len(rows)} crates)")


if __name__ == "__main__":
    main()
